-- Create the tour_guides table in Supabase
CREATE TABLE tour_guides (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  photo_url TEXT,
  gender TEXT,
  experience TEXT,
  languages TEXT,
  specialties TEXT,
  description TEXT,
  contact TEXT,
  price TEXT,
  rating NUMERIC DEFAULT 4.5,
  reviews INTEGER DEFAULT 0,
  verified BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add RLS (Row Level Security) policies to secure the table
ALTER TABLE tour_guides ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows anyone to read verified guides
CREATE POLICY "Anyone can read verified guides" 
ON tour_guides 
FOR SELECT 
USING (verified = TRUE);

-- Create a policy that allows authenticated users to create guide profiles
CREATE POLICY "Authenticated users can create guide profiles" 
ON tour_guides 
FOR INSERT 
TO authenticated 
WITH CHECK (true);

-- Create a policy that allows users to update their own guide profiles
CREATE POLICY "Users can update their own guide profiles" 
ON tour_guides 
FOR UPDATE 
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- Optional: Add a user_id column to associate guides with users
-- Uncomment this if you want to track which user created which guide profile
-- ALTER TABLE tour_guides ADD COLUMN user_id UUID REFERENCES auth.users;
